### ISSUE TITLE
There is no way of sending a body with a request

### ISSUE THREAD

**Issue by Dretch** [uwap/idris-http#18]
`Http.httpRequest` accepts `Request a`, where `a` is the type of the body of the request, but there is no way of passing a value for the body such that it gets sent in the request.

Do you have an idea for how this is supposed to work?

In my local hacked version I have just got rid of the type parameter from `Request`, and changed the type of `requestBody` into `String` -- but this is possibly not what you want (and really a byte array would be better than `String`)

**Comment by uwap** [comment]
@relrod Maybe we should hack on this this weekend?
